name: Request Firmware
description: Use this template to request firmware files for your product.
title: "[Firmware Request]: BRAND - ZW NUMBER - PRODUCT NUMBER"
body:
  - type: dropdown
    id: brand
    attributes:
      label: What brand is the request for?
      multiple: false
      options:
        - Enbrighten-GE
        - Honeywell
        - UltraPro
        - Jasco
    validations:
      required: true
  - type: input
    id: zwnumber
    attributes:
      label: ZW Number
      description: Please provide the ZW Number. See [this section](https://github.com/jascoproducts/firmware#identifying-your-product) of the repository readme for more info.
    validations:
      required: true
  - type: input
    id: prodnumber
    attributes:
      label: Product Number
      description: Please provide the Product (SKU) Number found on the device. If unavailable, please provide in the comments of your request as much relevant identifying information/screenshots as possible. See [this section](https://github.com/jascoproducts/firmware#identifying-your-product) of the repository readme for more info.
    validations:
      required: true
